[env:seeed_xiao_esp32c3]
platform = espressif32@6.5.0
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

; Partition table for RainMaker (requires more app space)
board_build.partitions = rainmaker.csv

; Enable USB CDC on Boot for Serial Monitor
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ; RainMaker requires this sometimes if not defined by board
    -DCONFIG_ESP_RMAKER_WORK_QUEUE_TASK_STACK=4096

; Monitor Filters
monitor_filters = esp32_exception_decoder

; Dependencies
lib_deps =
    ; SimpleBLE is often needed for provisioning via BLE
    SimpleBLE
